package BaseCbb.RegCbb.dsl

import org.json4s._
import org.json4s.native.Serialization
import org.json4s.native.JsonMethods._

/** Field IR for JSON output */
case class FieldIR(
  name: String,
  bitOffset: Int,
  bitWidth: Int,
  accessType: String,
  resetValue: BigInt,
  description: String,
  writeAction: String = "Normal",
  enumerations: Map[String, String] = Map()
)

/** Register IR for JSON output */
case class RegisterIR(
  name: String,
  byteOffset: String,
  byteSize: Int,
  description: String,
  group: String,
  fields: Seq[FieldIR]
)

/** Memory IR for JSON output */
case class MemoryIR(
  name: String,
  baseAddress: String,
  depth: Int,
  dataWidth: Int,
  byteSize: Long,
  memType: String,
  description: String
)

/** Register Block IR for JSON output */
case class RegBlockIR(
  displayName: String,
  deviceName: String,
  regBaseAddress: String,
  memBaseAddress: String,
  totalRegSize: Long,
  totalMemSize: Long,
  registers: Seq[RegisterIR],
  memories: Seq[MemoryIR]
)

/** JSON IR Generator */
object RegisterIRGenerator {
  implicit val formats: Formats = DefaultFormats.withBigInt

  private def accessToString(a: AccessType): String = a match {
    case AccessType.RO => "RO"
    case AccessType.WO => "WO"
    case AccessType.RW => "RW"
    case AccessType.RC => "RC"
    case AccessType.RS => "RS"
  }

  private def memAccessToString(a: MemoryAccessType): String = a match {
    case MemoryAccessType.SP => "SP"
    case MemoryAccessType.TP => "TP"
  }

  private def writeActionToString(a: WriteAction): String = a match {
    case WriteAction.Normal => "Normal"
    case WriteAction.OneToClear => "OneToClear"
    case WriteAction.OneToSet => "OneToSet"
    case WriteAction.OneToToggle => "OneToToggle"
    case WriteAction.ClearOnRead => "ClearOnRead"
  }

  /** Generate IR from address map */
  def generate(map: AddressMap): RegBlockIR = {
    val registers = map.registerAllocations.map { regAlloc =>
      val fields = regAlloc.fieldAllocations.map { fieldAlloc =>
        val field = fieldAlloc.field
        FieldIR(
          name = field.name,
          bitOffset = fieldAlloc.bitOffset,
          bitWidth = field.bitWidth,
          accessType = accessToString(field.access),
          resetValue = field.resetValue,
          description = field.description,
          writeAction = writeActionToString(field.writeAction),
          enumerations = field.enumerations.map { case (k, v) => k.toString -> s"${v._1}: ${v._2}" }
        )
      }

      RegisterIR(
        name = regAlloc.register.name,
        byteOffset = s"0x${regAlloc.byteOffset.toString(16)}",
        byteSize = regAlloc.byteSize,
        description = regAlloc.register.description,
        group = regAlloc.register.group.getOrElse(""),
        fields = fields
      )
    }

    val memories = map.memoryAllocations.map { memAlloc =>
      val mem = memAlloc.memory
      MemoryIR(
        name = mem.name,
        baseAddress = s"0x${mem.baseAddress.toString(16)}",
        depth = mem.depth,
        dataWidth = mem.dataWidth,
        byteSize = mem.byteSize.toLong,
        memType = memAccessToString(mem.memType),
        description = mem.description
      )
    }

    RegBlockIR(
      displayName = map.block.name,
      deviceName = map.block.deviceName,
      regBaseAddress = s"0x${map.block.regBaseAddress.toString(16)}",
      memBaseAddress = s"0x${map.block.memBaseAddress.toString(16)}",
      totalRegSize = map.totalRegByteSize.toLong,
      totalMemSize = map.totalMemByteSize.toLong,
      registers = registers,
      memories = memories
    )
  }

  /** Convert IR to pretty JSON string */
  def toJson(ir: RegBlockIR): String = {
    Serialization.writePretty(ir)
  }

  /** Convert IR to compact JSON string */
  def toJsonCompact(ir: RegBlockIR): String = {
    Serialization.write(ir)
  }

  /** Generate C header file content */
  def toCHeader(ir: RegBlockIR): String = {
    val sb = new StringBuilder
    val guard = s"${ir.deviceName.toUpperCase}_REG_H"

    sb ++= s"#ifndef $guard\n"
    sb ++= s"#define $guard\n\n"
    sb ++= s"/* ${ir.displayName} Register Map */\n"
    sb ++= s"/* Auto-generated by RegisterIRGenerator */\n\n"

    // Base addresses
    sb ++= s"/* Register Space Base Address */\n"
    sb ++= s"#define ${ir.deviceName.toUpperCase}_REG_BASE  ${ir.regBaseAddress}\n\n"
    sb ++= s"/* Memory Space Base Address */\n"
    sb ++= s"#define ${ir.deviceName.toUpperCase}_MEM_BASE  ${ir.memBaseAddress}\n\n"

    // Registers
    sb ++= s"/* ========================================= */\n"
    sb ++= s"/* Registers                                 */\n"
    sb ++= s"/* ========================================= */\n\n"

    for (reg <- ir.registers) {
      val offset = BigInt(reg.byteOffset.replace("0x", ""), 16)
      sb ++= s"/* ${reg.name} - ${reg.description} */\n"
      sb ++= s"#define ${ir.deviceName.toUpperCase}_${reg.name.toUpperCase}_REG \\\n"
      sb ++= s"  (${ir.deviceName.toUpperCase}_REG_BASE + 0x${offset.toString(16)})\n\n"

      // Fields
      for (field <- reg.fields) {
        val mask = if (field.bitWidth == 32) {
          "0xFFFFFFFF"
        } else {
          val m = ((1L << field.bitWidth) - 1).toLong << field.bitOffset
          s"0x${java.lang.Long.toHexString(m)}"
        }
        sb ++= s"#define ${ir.deviceName.toUpperCase}_${reg.name.toUpperCase}_${field.name.toUpperCase}_MASK  ${mask}\n"
        sb ++= s"#define ${ir.deviceName.toUpperCase}_${reg.name.toUpperCase}_${field.name.toUpperCase}_SHIFT ${field.bitOffset}\n"
        if (field.resetValue != 0) {
          sb ++= s"#define ${ir.deviceName.toUpperCase}_${reg.name.toUpperCase}_${field.name.toUpperCase}_RST  0x${field.resetValue.toString(16)}\n"
        }
      }
      sb ++= "\n"
    }

    // Memories
    if (ir.memories.nonEmpty) {
      sb ++= s"/* ========================================= */\n"
      sb ++= s"/* Memory Regions                            */\n"
      sb ++= s"/* ========================================= */\n\n"

      for (mem <- ir.memories) {
        sb ++= s"/* ${mem.name} - ${mem.description} */\n"
        sb ++= s"#define ${ir.deviceName.toUpperCase}_${mem.name.toUpperCase}_MEM  ${mem.baseAddress}\n"
        sb ++= s"#define ${ir.deviceName.toUpperCase}_${mem.name.toUpperCase}_DEPTH  ${mem.depth}\n"
        sb ++= s"#define ${ir.deviceName.toUpperCase}_${mem.name.toUpperCase}_WIDTH  ${mem.dataWidth}\n"
        sb ++= s"#define ${ir.deviceName.toUpperCase}_${mem.name.toUpperCase}_SIZE   ${mem.byteSize}\n\n"
      }
    }

    sb ++= s"#endif /* $guard */\n"
    sb.toString
  }
}
